CREATE DATABASE IF NOT EXISTS vegz CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE vegz;

CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,phone VARCHAR(100) NULL UNIQUE,email VARCHAR(255) NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,role ENUM('customer','shop','agent','admin') NOT NULL DEFAULT 'customer',
 active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS products (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,shop_id BIGINT UNSIGNED NULL,name VARCHAR(150) NOT NULL,category VARCHAR(80) NOT NULL,
 price DECIMAL(10,2) NOT NULL,unit VARCHAR(30) NOT NULL,image_url VARCHAR(1000),description TEXT,stock INT NOT NULL DEFAULT 0,
 active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_products_shop(shop_id),INDEX idx_products_active_stock(active,stock),FOREIGN KEY(shop_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,shop_id BIGINT UNSIGNED NULL,agent_id BIGINT UNSIGNED NULL,
 status ENUM('PAYMENT_PENDING','CONFIRMED','PREPARING','READY_FOR_PICKUP','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','REFUNDED') NOT NULL DEFAULT 'PAYMENT_PENDING',
 total DECIMAL(10,2) NOT NULL,address_json JSON NOT NULL,payment_status ENUM('PENDING','PAID','FAILED','REFUNDED') NOT NULL DEFAULT 'PENDING',
 payment_provider VARCHAR(40) NULL,payment_reference VARCHAR(255) NULL,idempotency_key VARCHAR(100) NULL UNIQUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(shop_id) REFERENCES users(id),FOREIGN KEY(agent_id) REFERENCES users(id),INDEX idx_orders_user_created(user_id,created_at),INDEX idx_orders_status(status)
);
CREATE TABLE IF NOT EXISTS order_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,quantity INT NOT NULL,
 unit_price DECIMAL(10,2) NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id)
);
CREATE TABLE IF NOT EXISTS payment_transactions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,provider VARCHAR(40) NOT NULL,provider_payment_id VARCHAR(255),
 amount DECIMAL(10,2) NOT NULL,status VARCHAR(30) NOT NULL,raw_response JSON NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES orders(id),INDEX idx_payment_order(order_id)
);
CREATE TABLE IF NOT EXISTS settlements (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,shop_id BIGINT UNSIGNED NULL,agent_id BIGINT UNSIGNED NULL,
 shop_amount DECIMAL(10,2) NOT NULL DEFAULT 0,agent_amount DECIMAL(10,2) NOT NULL DEFAULT 0,admin_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
 status VARCHAR(30) NOT NULL DEFAULT 'PENDING',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(shop_id) REFERENCES users(id),FOREIGN KEY(agent_id) REFERENCES users(id)
);

INSERT IGNORE INTO products(name,category,price,unit,description,stock) VALUES
('Tomato','Vegetables',40,'kg','Fresh red tomatoes',100),('Potato','Root',35,'kg','Farm fresh potatoes',100),
('Spinach','Leafy',25,'bunch','Fresh green spinach',100),('Carrot','Root',60,'kg','Crisp fresh carrots',100);