import "dotenv/config";
import express from "express"; import cors from "cors"; import helmet from "helmet"; import bcrypt from "bcryptjs"; import jwt from "jsonwebtoken"; import mysql from "mysql2/promise"; import {z} from "zod";
const app=express(),port=Number(process.env.PORT||4000),jwtSecret=process.env.JWT_SECRET; if(!jwtSecret) throw new Error("JWT_SECRET is required");
const pool=mysql.createPool(process.env.DATABASE_URL||"mysql://vegz:change-me@localhost:3306/vegz");
const origins=(process.env.CORS_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean);
app.use(helmet()); app.use(cors({origin:(o,cb)=>!o||origins.includes(o)?cb(null,true):cb(new Error("CORS origin denied"))})); app.use(express.json({limit:"1mb"}));
type Req=express.Request&{user?:{id:number;role:string}}; const auth=(req:Req,res:express.Response,next:express.NextFunction)=>{try{const h=req.headers.authorization;if(!h?.startsWith("Bearer "))return res.status(401).json({message:"Authentication required"});req.user=jwt.verify(h.slice(7),jwtSecret) as any;next()}catch{return res.status(401).json({message:"Invalid or expired token"})}};
const roles=(...allowed:string[])=>(req:Req,res:express.Response,next:express.NextFunction)=>{if(!req.user||!allowed.includes(req.user.role))return res.status(403).json({message:"Insufficient permissions"});next()};
const asyncRoute=(fn:any)=>(req:express.Request,res:express.Response,next:express.NextFunction)=>Promise.resolve(fn(req,res,next)).catch(next);
app.get("/health",asyncRoute(async(_:any,res:any)=>{try{await pool.query("SELECT 1");res.json({status:"ok",database:"ok"})}catch{res.status(503).json({status:"degraded",database:"unavailable"})}}));

const registerSchema=z.object({name:z.string().min(2).max(100),phone:z.string().min(5).max(100),password:z.string().min(8).max(100),email:z.string().email().optional()});
app.post("/api/auth/register",asyncRoute(async(req:any,res:any)=>{const p=registerSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:"Invalid registration details"});const hash=await bcrypt.hash(p.data.password,12);try{const[r]=await pool.execute<mysql.ResultSetHeader>("INSERT INTO users(name,phone,email,password_hash,role) VALUES(?,?,?,?,'customer')",[p.data.name,p.data.phone,p.data.email||null,hash]);res.status(201).json({success:true,user:{id:r.insertId,name:p.data.name,phone:p.data.phone,email:p.data.email||null,role:"customer"}})}catch(e:any){if(e.code==="ER_DUP_ENTRY")return res.status(409).json({message:"Account already exists"});throw e}}));
const loginSchema=z.object({username:z.string().min(3).max(100),password:z.string().min(1).max(100)});
app.post("/api/auth/login",asyncRoute(async(req:any,res:any)=>{const p=loginSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:"Invalid login details"});const[rows]=await pool.execute<mysql.RowDataPacket[]>("SELECT id,name,phone,email,password_hash,role,active FROM users WHERE phone=? OR email=? LIMIT 1",[p.data.username,p.data.username]);const u=rows[0];if(!u||!u.active||!(await bcrypt.compare(p.data.password,u.password_hash)))return res.status(401).json({message:"Invalid credentials"});res.json({token:jwt.sign({id:u.id,role:u.role},jwtSecret,{expiresIn:"7d"}),user:{id:u.id,name:u.name,phone:u.phone,email:u.email,role:u.role}})}));
app.get("/api/me",auth,asyncRoute(async(req:Req,res:any)=>{const[rows]=await pool.execute<mysql.RowDataPacket[]>("SELECT id,name,phone,email,role FROM users WHERE id=?",[req.user!.id]);if(!rows[0])return res.status(404).json({message:"User not found"});res.json(rows[0])}));

app.get("/api/products",asyncRoute(async(_:any,res:any)=>{const[rows]=await pool.query("SELECT id,name,category,price,unit,image_url AS imageUrl,description,stock,shop_id AS shopId FROM products WHERE active=1 AND stock>0 ORDER BY name");res.json(rows)}));
app.get("/api/products/:id",asyncRoute(async(req:any,res:any)=>{const[rows]=await pool.execute<mysql.RowDataPacket[]>("SELECT id,name,category,price,unit,image_url AS imageUrl,description,stock,shop_id AS shopId FROM products WHERE id=? AND active=1",[req.params.id]);if(!rows[0])return res.status(404).json({message:"Product not found"});res.json(rows[0])}));

const orderSchema=z.object({items:z.array(z.object({productId:z.coerce.number().int().positive(),quantity:z.number().int().positive().max(100)})).min(1),address:z.object({name:z.string().min(2),phone:z.string().min(5),line1:z.string().min(3),city:z.string().min(2),state:z.string().min(2),pincode:z.string().min(4).max(10)})});
app.post("/api/orders",auth,asyncRoute(async(req:Req,res:any)=>{const p=orderSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:"Invalid order"});const key=String(req.headers["idempotency-key"]||"").slice(0,100)||null;if(key){const[existing]=await pool.execute<mysql.RowDataPacket[]>("SELECT id,status,total FROM orders WHERE idempotency_key=?",[key]);if(existing[0])return res.status(200).json(existing[0])}const conn=await pool.getConnection();try{await conn.beginTransaction();const ids=p.data.items.map(x=>x.productId);const[products]=await conn.query<mysql.RowDataPacket[]>(`SELECT id,name,price,stock,shop_id FROM products WHERE active=1 AND id IN (${ids.map(()=>"?").join(",")}) FOR UPDATE`,ids);const map=new Map(products.map(x=>[Number(x.id),x]));let total=0;let shopId:number|null=null;for(const i of p.data.items){const pr=map.get(i.productId);if(!pr||Number(pr.stock)<i.quantity)throw new Error("PRODUCT_UNAVAILABLE");if(pr.shop_id&&shopId&&Number(pr.shop_id)!==shopId)throw new Error("MULTI_SHOP_ORDER_NOT_SUPPORTED_YET");shopId=pr.shop_id?Number(pr.shop_id):null;total+=Number(pr.price)*i.quantity}const[o]=await conn.execute<mysql.ResultSetHeader>("INSERT INTO orders(user_id,shop_id,status,total,address_json,idempotency_key) VALUES (?,?,'PAYMENT_PENDING',?,?,?)",[req.user!.id,shopId,total,JSON.stringify(p.data.address),key]);for(const i of p.data.items){const pr=map.get(i.productId)!;await conn.execute("INSERT INTO order_items(order_id,product_id,quantity,unit_price) VALUES(?,?,?,?)",[o.insertId,i.productId,i.quantity,pr.price]);await conn.execute("UPDATE products SET stock=stock-? WHERE id=?",[i.quantity,i.productId])}await conn.commit();res.status(201).json({id:o.insertId,status:"PAYMENT_PENDING",paymentStatus:"PENDING",total})}catch(e){await conn.rollback();if(e instanceof Error&&e.message==="PRODUCT_UNAVAILABLE")return res.status(409).json({message:"Product unavailable"});if(e instanceof Error&&e.message==="MULTI_SHOP_ORDER_NOT_SUPPORTED_YET")return res.status(409).json({message:"Cart items must currently belong to one shop"});throw e}finally{conn.release()}}));
async function hydrateOrders(rows:any[]){for(const o of rows){o.address=typeof o.address==="string"?JSON.parse(o.address):o.address;const[items]=await pool.execute("SELECT oi.product_id AS productId,p.name,oi.quantity,oi.unit_price AS price FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=?",[o.id]);o.items=items}return rows}
app.get("/api/orders",auth,asyncRoute(async(req:Req,res:any)=>{const[rows]=await pool.execute<mysql.RowDataPacket[]>("SELECT id,status,total,address_json AS address,payment_status AS paymentStatus,created_at AS createdAt,updated_at AS updatedAt FROM orders WHERE user_id=? ORDER BY created_at DESC",[req.user!.id]);res.json(await hydrateOrders(rows))}));
app.get("/api/orders/:id",auth,asyncRoute(async(req:Req,res:any)=>{const sql=req.user!.role==="customer"?"SELECT id,status,total,address_json AS address,payment_status AS paymentStatus,created_at AS createdAt,updated_at AS updatedAt FROM orders WHERE id=? AND user_id=?":"SELECT id,status,total,address_json AS address,payment_status AS paymentStatus,created_at AS createdAt,updated_at AS updatedAt,user_id AS userId,shop_id AS shopId,agent_id AS agentId FROM orders WHERE id=?";const args=req.user!.role==="customer"?[req.params.id,req.user!.id]:[req.params.id];const[rows]=await pool.execute<mysql.RowDataPacket[]>(sql,args);if(!rows[0])return res.status(404).json({message:"Order not found"});res.json((await hydrateOrders(rows))[0])}));

const statusSchema=z.object({status:z.enum(["CONFIRMED","PREPARING","READY_FOR_PICKUP","OUT_FOR_DELIVERY","DELIVERED","CANCELLED"])});
app.patch("/api/shop/orders/:id/status",auth,roles("shop","admin"),asyncRoute(async(req:Req,res:any)=>{const p=statusSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:"Invalid status"});const where=req.user!.role==="shop"?"AND shop_id=?":"";const args=req.user!.role==="shop"?[p.data.status,req.params.id,req.user!.id]:[p.data.status,req.params.id];const[r]=await pool.execute<mysql.ResultSetHeader>(`UPDATE orders SET status=? WHERE id=? ${where}`,args);if(!r.affectedRows)return res.status(404).json({message:"Order not found"});res.json({success:true,status:p.data.status})}));
app.patch("/api/agent/orders/:id/status",auth,roles("agent","admin"),asyncRoute(async(req:Req,res:any)=>{const p=statusSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:"Invalid status"});const where=req.user!.role==="agent"?"AND (agent_id=? OR agent_id IS NULL)":"";const args=req.user!.role==="agent"?[p.data.status,req.params.id,req.user!.id]:[p.data.status,req.params.id];const[r]=await pool.execute<mysql.ResultSetHeader>(`UPDATE orders SET status=?,agent_id=COALESCE(agent_id,?) WHERE id=? ${where}`,req.user!.role==="agent"? [p.data.status,req.user!.id,req.params.id,req.user!.id] : [p.data.status,null,req.params.id]);if(!r.affectedRows)return res.status(404).json({message:"Order not found"});res.json({success:true,status:p.data.status})}));

const productSchema=z.object({name:z.string().min(2).max(150),category:z.string().min(2).max(80),price:z.number().nonnegative(),unit:z.string().min(1).max(30),description:z.string().max(5000).optional(),stock:z.number().int().nonnegative(),imageUrl:z.string().url().optional()});
app.post("/api/shop/products",auth,roles("shop","admin"),asyncRoute(async(req:Req,res:any)=>{const p=productSchema.safeParse(req.body);if(!p.success)return res.status(400).json({message:"Invalid product"});const[r]=await pool.execute<mysql.ResultSetHeader>("INSERT INTO products(shop_id,name,category,price,unit,description,stock,image_url) VALUES(?,?,?,?,?,?,?,?)",[req.user!.role==="shop"?req.user!.id:null,p.data.name,p.data.category,p.data.price,p.data.unit,p.data.description||null,p.data.stock,p.data.imageUrl||null]);res.status(201).json({id:r.insertId})}));
app.patch("/api/shop/products/:id",auth,roles("shop","admin"),asyncRoute(async(req:Req,res:any)=>{const p=productSchema.partial().safeParse(req.body);if(!p.success)return res.status(400).json({message:"Invalid product"});const fields:any={name:p.data.name,category:p.data.category,price:p.data.price,unit:p.data.unit,description:p.data.description,stock:p.data.stock,image_url:p.data.imageUrl};const set=Object.entries(fields).filter(([,v])=>v!==undefined);if(!set.length)return res.status(400).json({message:"No changes"});const where=req.user!.role==="shop"?" AND shop_id=?":"";const vals=set.map(x=>x[1]);const[r]=await pool.execute<mysql.ResultSetHeader>(`UPDATE products SET ${set.map(([k])=>k+"=?").join(",")} WHERE id=?${where}`,req.user!.role==="shop"?[...vals,req.params.id,req.user!.id]:[...vals,req.params.id]);if(!r.affectedRows)return res.status(404).json({message:"Product not found"});res.json({success:true})}));

app.get("/api/admin/dashboard",auth,roles("admin"),asyncRoute(async(_:Req,res:any)=>{const[[users]]=await pool.query<mysql.RowDataPacket[]>("SELECT COUNT(*) AS count FROM users");const[[products]]=await pool.query<mysql.RowDataPacket[]>("SELECT COUNT(*) AS count FROM products WHERE active=1");const[[orders]]=await pool.query<mysql.RowDataPacket[]>("SELECT COUNT(*) AS count FROM orders");const[[revenue]]=await pool.query<mysql.RowDataPacket[]>("SELECT COALESCE(SUM(total),0) AS total FROM orders WHERE payment_status='PAID'");res.json({users:Number(users.count),products:Number(products.count),orders:Number(orders.count),revenue:Number(revenue.total)})}));
app.get("/api/admin/orders",auth,roles("admin"),asyncRoute(async(_:Req,res:any)=>{const[rows]=await pool.query("SELECT id,user_id AS userId,shop_id AS shopId,agent_id AS agentId,status,total,payment_status AS paymentStatus,created_at AS createdAt FROM orders ORDER BY created_at DESC LIMIT 100");res.json(rows)}));

app.use((err:any,_:any,res:any,_next:any)=>{console.error(err);res.status(500).json({message:"Internal server error"})});app.use((_:any,res:any)=>res.status(404).json({message:"Not found"}));
app.listen(port,()=>console.log("Vegz API listening on :"+port));