import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const API=import.meta.env.VITE_API_BASE_URL||"https://api.vegz.online";
type Product={id:number|string;name:string;category:string;price:number;unit:string;imageUrl?:string;description?:string;stock:number};type Cart={product:Product;quantity:number};
async function api<T>(path:string,init:RequestInit={}){const token=localStorage.getItem("vegz-token");const r=await fetch(API+path,{...init,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...(init.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d as T}
function App(){const[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<Cart[]>(()=>JSON.parse(localStorage.getItem("vegz-cart")||"[]")),[search,setSearch]=useState(""),[category,setCategory]=useState("All"),[orders,setOrders]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[logged,setLogged]=useState(!!localStorage.getItem("vegz-token")),[phone,setPhone]=useState(""),[otp,setOtp]=useState(""),[devOtp,setDevOtp]=useState(""),[otpSent,setOtpSent]=useState(false),[showAuth,setShowAuth]=useState(false),[showCart,setShowCart]=useState(false),[showAddress,setShowAddress]=useState(false),[payBusy,setPayBusy]=useState(false),[address,setAddress]=useState({name:"",phone:"",line1:"",city:"Bengaluru",state:"Karnataka",pincode:""});
useEffect(()=>{api<Product[]>("/api/products").then(setProducts).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);useEffect(()=>localStorage.setItem("vegz-cart",JSON.stringify(cart)),[cart]);
const categories=useMemo(()=>["All",...Array.from(new Set(products.map(p=>p.category)))],[products]);const filtered=products.filter(p=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase()));const total=cart.reduce((s,x)=>s+x.product.price*x.quantity,0);const count=cart.reduce((s,x)=>s+x.quantity,0);
function add(p:Product){setCart(c=>{const x=c.find(i=>String(i.product.id)===String(p.id));return x?c.map(i=>String(i.product.id)===String(p.id)?{...i,quantity:i.quantity+1}:i):[...c,{product:p,quantity:1}]});setShowCart(true)}
function remove(id:string){setCart(c=>c.flatMap(i=>String(i.product.id)===id?(i.quantity>1?[{...i,quantity:i.quantity-1}]:[]):[i]))}
async function sendOtp(){if(!/^\\+?[0-9]{10,15}$/.test(phone)){alert("Enter a valid mobile number.");return}try{const d=await api<any>("/api/auth/request-otp",{method:"POST",body:JSON.stringify({phone})});setOtpSent(true);setDevOtp(d.devOtp||"");if(d.devOtp)alert("Development OTP: "+d.devOtp)}catch(e:any){alert(e.message)}}
async function verifyOtp(){if(!/^\\d{6}$/.test(otp)){alert("Enter the 6-digit OTP.");return}try{const d=await api<any>("/api/auth/verify-otp",{method:"POST",body:JSON.stringify({phone,otp})});localStorage.setItem("vegz-token",d.token);setLogged(true);setShowAuth(false);setOtpSent(false);setOtp("");setShowAddress(true)}catch(e:any){alert(e.message)}}
async function pay(){if(!address.name||!address.phone||!address.line1||!address.city||!address.state||!address.pincode){alert("Complete the delivery address.");return}setPayBusy(true);try{const d=await api<{id:number}>("/api/orders",{method:"POST",headers:{"Idempotency-Key":Date.now()+"-"+Math.random().toString(36).slice(2)},body:JSON.stringify({items:cart.map(x=>({productId:Number(x.product.id),quantity:x.quantity})),address})});alert("Order #"+d.id+" created successfully.");setCart([]);setShowAddress(false);setShowCart(false);loadOrders()}catch(e:any){alert(e.message)}finally{setPayBusy(false)}}
async function loadOrders(){if(!logged)return;try{setOrders(await api<any[]>("/api/orders"))}catch{}}
function beginCheckout(){setShowCart(true);if(!logged)setShowAuth(true);else setShowAddress(true)}
return <><header><div className="brand">🌱 Vegz</div><nav><a href="#shop">Shop</a><a href="#orders" onClick={loadOrders}>Orders</a><a href="#about">About</a></nav><button className="cart-button" onClick={()=>setShowCart(true)}>🛒 {count} · ₹{total.toFixed(0)}</button></header>
<main><section id="shop" className="section shop-first"><div className="shop-heading"><span className="pill">Fresh • Local • Delivered</span><h1>Fresh vegetables, ready to order.</h1><p>Choose your vegetables first. Login is only required when you continue to checkout.</p></div><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search vegetables..."/><div className="chips">{categories.map(c=><button className={c===category?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div></div>{error&&<div className="error">{error}</div>}{loading?<p>Loading products…</p>:<div className="grid">{filtered.map(p=><article className="card" key={p.id}><div className="photo">{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<span>🥬</span>}</div><small>{p.category}</small><h3>{p.name}</h3><div className="row"><div><b>₹{Number(p.price).toFixed(0)}</b><span> / {p.unit}</span></div><button onClick={()=>add(p)}>Add</button></div></article>)}</div>}</section>
<section id="orders" className="section"><h2>Your orders</h2>{orders.length===0?<p>Login and place an order to see order history here.</p>:<div className="orders">{orders.map(o=><div className="order" key={o.id}><b>Order #{o.id}</b><span>{o.status}</span><strong>₹{Number(o.total).toFixed(2)}</strong></div>)}</div>}</section><section id="about" className="about"><h2>Vegz</h2><p>Fresh vegetables from shops and farmers through one Vegz platform.</p></section></main>
{showCart&&<div className="overlay" onClick={()=>setShowCart(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>Your cart</h2><button onClick={()=>setShowCart(false)}>×</button></div>{cart.length===0?<p>Your cart is empty.</p>:<>{cart.map(x=><div className="cart-item" key={x.product.id}><div className="mini-photo">{x.product.imageUrl?<img src={x.product.imageUrl} alt=""/>:<span>🥕</span>}</div><div className="cart-info"><b>{x.product.name}</b><small>₹{x.product.price}/{x.product.unit}</small><div className="qty"><button onClick={()=>remove(String(x.product.id))}>−</button><span>{x.quantity}</span><button onClick={()=>add(x.product)}>+</button></div></div><strong>₹{(x.product.price*x.quantity).toFixed(0)}</strong></div>)}<div className="cart-total"><span>Total</span><b>₹{total.toFixed(0)}</b></div><button className="cta full" onClick={beginCheckout}>Continue to checkout</button></>}</aside></div>}
{showAuth&&<div className="modal"><div className="modal-card"><button className="close" onClick={()=>setShowAuth(false)}>×</button><h2>Login with mobile</h2><p>We only ask for login when you checkout.</p><input placeholder="Mobile number" value={phone} onChange={e=>setPhone(e.target.value)} disabled={otpSent}/>{otpSent&&<input placeholder="6-digit OTP" value={otp} onChange={e=>setOtp(e.target.value)} maxLength={6}/>} {!otpSent?<button className="cta full" onClick={sendOtp}>Send OTP</button>:<button className="cta full" onClick={verifyOtp}>Verify OTP</button>}{devOtp&&<small className="dev">Development OTP: {devOtp}</small>}</div></div>}
{showAddress&&<div className="modal"><div className="modal-card"><button className="close" onClick={()=>setShowAddress(false)}>×</button><h2>Delivery & payment</h2><input placeholder="Full name" value={address.name} onChange={e=>setAddress({...address,name:e.target.value})}/><input placeholder="Mobile number" value={address.phone||phone} onChange={e=>setAddress({...address,phone:e.target.value})}/><input placeholder="House / street / area" value={address.line1} onChange={e=>setAddress({...address,line1:e.target.value})}/><input placeholder="City" value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/><input placeholder="State" value={address.state} onChange={e=>setAddress({...address,state:e.target.value})}/><input placeholder="PIN code" value={address.pincode} onChange={e=>setAddress({...address,pincode:e.target.value})}/><div className="pay-summary"><span>Order total</span><b>₹{total.toFixed(0)}</b></div><button className="cta full" disabled={payBusy} onClick={pay}>{payBusy?"Processing…":"Pay ₹"+total.toFixed(0)}</button><small className="dev">Development payment flow. Connect the production gateway before launch.</small></div></div>}
<div className="checkout"><span>{count?count+" items · ₹"+total.toFixed(0):"Select vegetables to start"}</span><button disabled={!cart.length} onClick={beginCheckout}>Checkout</button></div></>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);