import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const API=import.meta.env.VITE_API_BASE_URL||"https://api.vegz.online";
type Product={id:number|string;name:string;category:string;price:number;unit:string;imageUrl?:string;description?:string;stock:number}; type Cart={product:Product;quantity:number};
async function api<T>(path:string,init:RequestInit={}){const token=localStorage.getItem("vegz-token");const r=await fetch(API+path,{...init,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...(init.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d as T}
function App(){const[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<Cart[]>(()=>JSON.parse(localStorage.getItem("vegz-cart")||"[]")),[search,setSearch]=useState(""),[category,setCategory]=useState("All"),[orders,setOrders]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
useEffect(()=>{api<Product[]>("/api/products").then(setProducts).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);useEffect(()=>localStorage.setItem("vegz-cart",JSON.stringify(cart)),[cart]);
const categories=useMemo(()=>["All",...Array.from(new Set(products.map(p=>p.category)))],[products]);const filtered=products.filter(p=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase()));const total=cart.reduce((s,x)=>s+x.product.price*x.quantity,0);
function add(p:Product){setCart(c=>{const x=c.find(i=>String(i.product.id)===String(p.id));return x?c.map(i=>String(i.product.id)===String(p.id)?{...i,quantity:i.quantity+1}:i):[...c,{product:p,quantity:1}]})}
async function checkout(){const token=localStorage.getItem("vegz-token");if(!token){alert("Please sign in first.");return}try{const d=await api<{id:number}>("/api/orders",{method:"POST",body:JSON.stringify({items:cart.map(x=>({productId:Number(x.product.id),quantity:x.quantity})),address:{name:"Vegz Customer",phone:"0000000000",line1:"Update address",city:"Bengaluru",state:"Karnataka",pincode:"560001"}})});alert("Order #"+d.id+" created.");setCart([]);loadOrders()}catch(e:any){alert(e.message)}} async function loadOrders(){try{setOrders(await api<any[]>("/api/orders"))}catch{}}
return <><header><div className="brand">🌱 Vegz</div><nav><a href="#shop">Shop</a><a href="#orders" onClick={loadOrders}>Orders</a><a href="#about">About</a></nav><div className="cart">🛒 {cart.reduce((s,x)=>s+x.quantity,0)} · ₹{total.toFixed(0)}</div></header><main><section className="hero"><div><span className="pill">Fresh • Local • Delivered</span><h1>Vegetables from farm to your doorstep.</h1><p>Browse fresh produce and order through the same Vegz API used by the mobile app.</p><a className="cta" href="#shop">Shop vegetables</a></div><div className="hero-card">🥕<strong>Fresh produce</strong><span>Simple marketplace experience</span></div></section><section id="shop" className="section"><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search vegetables..."/><div className="chips">{categories.map(c=><button className={c===category?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div></div>{error&&<div className="error">{error}</div>}{loading?<p>Loading products…</p>:<div className="grid">{filtered.map(p=><article className="card" key={p.id}><div className="photo">{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<span>🥬</span>}</div><small>{p.category}</small><h3>{p.name}</h3><p>{p.description||"Fresh produce from Vegz."}</p><div className="row"><b>₹{Number(p.price).toFixed(0)}/{p.unit}</b><button onClick={()=>add(p)}>Add</button></div></article>)}</div>}</section><section id="orders" className="section"><h2>Your orders</h2>{orders.length===0?<p>Login and place an order to see order history here.</p>:<div className="orders">{orders.map(o=><div className="order" key={o.id}><b>Order #{o.id}</b><span>{o.status}</span><strong>₹{Number(o.total).toFixed(2)}</strong></div>)}</div>}</section><section id="about" className="about"><h2>One Vegz platform</h2><p>The customer web app and Android app share the same backend and MySQL data model.</p></section></main><div className="checkout"><span>{cart.length?cart.reduce((s,x)=>s+x.quantity,0)+" items · ₹"+total.toFixed(0):"Cart is empty"}</span><button disabled={!cart.length} onClick={checkout}>Place order</button></div></>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);